force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Medicare_Provider_Number__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Provider_Number__c</fullName>
    <label>Medicare Provider Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Practitioner_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_s_Name__c</fullName>
    <label>Practitioner&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Internal Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to Applicant</fullName>
            </value>
            <value>
                <fullName>Submitted to HREC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationController.cls
public with sharing class ApplicationController {
  @AuraEnabled(cacheable=true)
  public static List<Application__c> getApplicationList() {
    return [
      SELECT
        Id,
        Name,
        Status__c,
        Practitioner_s_Name__c,
        Medicare_Provider_Number__c,
        Address__c,
        createddate
      FROM Application__c
      WITH SECURITY_ENFORCED
      ORDER BY createddate DESC
      LIMIT 10
    ];
  }

  @AuraEnabled(cacheable=true)
  public static List<Application__c> findApplications(String searchKey) {
    String key = '%' + searchKey + '%';
    return [
      SELECT
        Id,
        Name,
        Status__c,
        Practitioner_s_Name__c,
        Medicare_Provider_Number__c
      FROM Application__c
      WHERE Name LIKE :key
      WITH SECURITY_ENFORCED
      LIMIT 10
    ];
  }

  @AuraEnabled(cacheable=true)
  public static Application__c getSingleApplication() {
    return [
      SELECT
        Id,
        Name,
        Status__c,
        Practitioner_s_Name__c,
        Medicare_Provider_Number__c
      FROM Application__c
      WITH SECURITY_ENFORCED
      LIMIT 1
    ];
  }
}