force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_Number__c</fullName>
    <label>AHPRA Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Practitioner_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_s_Name__c</fullName>
    <label>Practitioner&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvocableNIIMDeclarationTest.cls
@IsTest
public with sharing class InvocableNIIMDeclarationTest{
	@isTest
	static void myInvocableTest(){
        //insert a test Application
        Application__c a = new Application__c(email__c = 'burnside.mike@gmail.com', Practitioner_s_name__c = 'xx', AHPRA_Number__c = 'MED0000000000');
		insert a;
		
        Test.StartTest();
		InvocableNIIMGenerateDeclaration.Requests argument;
		argument = new InvocableNIIMGenerateDeclaration.Requests();
		argument.email = 'burnside.mike@gmail.com';
		argument.applicationId = a.id;

		List<String> teststr = new List<String>();
		teststr = InvocableNIIMGenerateDeclaration.generate(new List<InvocableNIIMGenerateDeclaration.Requests>{argument});
		Test.stopTest();
		
		System.assert(teststr[0] == 'Completed');

		// InvocableNIIMApplicationEmailSender.Requests r = new InvocableNIIMApplicationEmailSender.Requests();
		// r.email='burnside.mike@gmail.com';
		// r.applicationId=a.id;
		// req.add(r);
		// List<String> s = InvocableNIIMApplicationEmailSender.send(req);
		// //s=InvocableNIIMApplicationEmailSender.send(req);
	}
}