force-app/main/default/objects/App_Good__c/App_Good__c.object-meta.xml
<CustomObject>
    <label>App-Good</label>
    <nameField>
        <displayFormat>AG-{000000}</displayFormat>
        <label>App-Good Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App-Goods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Good__c/fields/App_Good_Indications__c.field-meta.xml
<CustomField>
    <fullName>App_Good_Indications__c</fullName>
    <label>App Good Indications</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neuropathic Pain</fullName>
            </value>
            <value>
                <fullName>Cancer Related Pain</fullName>
            </value>
            <value>
                <fullName>Chemotherapy induced nausea &amp; Vomiting (CINV)</fullName>
            </value>
            <value>
                <fullName>Anxiety Disorder including PTSD</fullName>
            </value>
            <value>
                <fullName>Autism / ASD</fullName>
            </value>
            <value>
                <fullName>Insomnia</fullName>
            </value>
            <value>
                <fullName>Parkinsons</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/App_Good_Indications_Description__c.field-meta.xml
<CustomField>
    <fullName>App_Good_Indications_Description__c</fullName>
    <label>App Good Indications Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>App-Goods</relationshipLabel>
    <relationshipName>App_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Approved_Good_Alternative__c.field-meta.xml
<CustomField>
    <fullName>Approved_Good_Alternative__c</fullName>
    <description>Is there an approved good for the same indication as what you applying to use the unapproved good for?</description>
    <inlineHelpText>Is there an approved good for the same indication as what you applying to use the unapproved good for?</inlineHelpText>
    <label>Approved Good Alternative?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Approved_In_Other_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Approved_In_Other_Jurisdiction__c</fullName>
    <label>Approved In Other Jurisdiction?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Clinical_Justification__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Justification__c</fullName>
    <description>Clinical justification for using the unapproved good. This should address expected benefits of the proposed medicine versus its potential risks, including evidence1 of:
- the unapproved good’s suitability for the intended indication
- the unapproved good’s efficacy and expected benefits
- any unknown or expected adverse effects, risks and safety issues
- related toxicology</description>
    <inlineHelpText>Clinical justification for using the unapproved good. This should address expected benefits of the proposed medicine versus its potential risks</inlineHelpText>
    <label>Clinical Justification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Dosage_Form__c.field-meta.xml
<CustomField>
    <fullName>Dosage_Form__c</fullName>
    <label>Dosage Form</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Dosage_Range__c.field-meta.xml
<CustomField>
    <fullName>Dosage_Range__c</fullName>
    <label>Dosage Range</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Expected_Duration_Of_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_Of_Treatment__c</fullName>
    <label>Expected Duration Of Treatment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Justification_Not_Using_Alternative__c.field-meta.xml
<CustomField>
    <fullName>Justification_Not_Using_Alternative__c</fullName>
    <description>Why is the approved good inappropriate or unsuitable for use?
Why is the proposed unapproved good a more appropriate option than an approved available alternative?</description>
    <inlineHelpText>Why is the approved good inappropriate or unsuitable for use?
Why is the proposed unapproved good a more appropriate option than an approved available alternative?</inlineHelpText>
    <label>Justification Not Using Alternative</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Product_Company__c.field-meta.xml
<CustomField>
    <fullName>Product_Company__c</fullName>
    <label>Product Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Product_Trade_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Trade_Name__c</fullName>
    <label>Product Trade Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Seriousness__c.field-meta.xml
<CustomField>
    <fullName>Seriousness__c</fullName>
    <label>Seriousness</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <label>Sponsor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Tried_Will_Try_Approved_Alternative__c.field-meta.xml
<CustomField>
    <fullName>Tried_Will_Try_Approved_Alternative__c</fullName>
    <label>Tried/Will Try Approved Alternative</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_Number__c</fullName>
    <label>AHPRA Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Applied_To_Other_HREC_In_Past_12_Months__c.field-meta.xml
<CustomField>
    <fullName>Applied_To_Other_HREC_In_Past_12_Months__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Applied To Other HREC In Past 12 Months</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Commercial_Interest__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commercial Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Medicare_Provider_Number__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Provider_Number__c</fullName>
    <label>Medicare Provider Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Practitioner_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_s_Name__c</fullName>
    <label>Practitioner&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Professional_Association_Membership__c.field-meta.xml
<CustomField>
    <fullName>Professional_Association_Membership__c</fullName>
    <label>Professional Association Membership #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Qualifications_and_Expertise__c.field-meta.xml
<CustomField>
    <fullName>Qualifications_and_Expertise__c</fullName>
    <label>Qualifications and Expertise</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Risk_Management_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Risk_Management_Strategy__c</fullName>
    <description>How will risks associated with the use of the unapproved good be managed? This should address:
Process of obtaining informed consent from patients
Monitoring and reporting that will be undertaken (include details of interval and duration of monitoring)
Process of investigating and reporting adverse events</description>
    <label>Risk Management Strategy</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Sites__c.field-meta.xml
<CustomField>
    <fullName>Sites__c</fullName>
    <inlineHelpText>Sites at which the unapproved goods will be prescribed (list all addresses)</inlineHelpText>
    <label>Sites</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for Internal Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to Applicant</fullName>
            </value>
            <value>
                <fullName>Submitted to HREC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Changes_Required__c/Changes_Required__c.object-meta.xml
<CustomObject>
    <label>Changes Required</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Concern Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Changes REquired</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Changes_Required__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Concerns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Changes_Required__c/fields/Change_Required__c.field-meta.xml
<CustomField>
    <fullName>Change_Required__c</fullName>
    <label>Change Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Changes_Required__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Evidence of Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Concern__c/Concern__c.object-meta.xml
<CustomObject>
    <label>Concern</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Concern Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concerns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Concern__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Concerns</relationshipLabel>
    <relationshipName>Concerns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NIIMApplicationHelper.cls
global class NIIMApplicationHelper{
	/**
	 * Send out the startup object attachments to the specified email 
	 * @param {String} applicationId The Id of the Application__c
	 * @param {String} emailAddress The email address of the recipient
	 */
	global static void sendApplicationSummary(String applicationId, String emailAddress){
		Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
		// Set the recipient address
		message.setToAddresses(new List<String>{emailAddress});
		//Dosage__c,
		//Dosage_Form__c,
		String htmlstr = '<H2>Thankyou for your application.</H2><h3>Below is a summary of the information we received, including the attachments you provided.</h3>';
		htmlstr+='<h3>Please also find attached a declaration that you will need to sign and upload.</h3>';
		
		htmlstr += '<p>You can upload your declaration to our secure portal at the following link</p>';

		//htmlstr+='<p>https://niimportal.force.com/NIIMApplication/s/flowappdeclaration?varApplicationId='+applicationId+'</p>';
		//htmlstr+='<p>https://preprod-niimportal.cs114.force.com/NIIMApplication/s/flowappdeclaration?varApplicationId='+applicationId+'</p>';
		htmlstr+='<p>https://mbdevp1-niimportal.cs58.force.com/NIIMApplication/s/flowappdeclaration?varApplicationId='+applicationId+'</p>';



		htmlstr += '<p>You can update your application on our secure portal at the following link</p>';

		
		//htmlstr+='<p>https://niimportal.force.com/NIIMApplication/s/flowapplicationupdate?varApplicationId='+applicationId+'</p>';
		//htmlstr+='<p>https://preprod-niimportal.cs114.force.com/NIIMApplication/s/flowapplicationupdate?varApplicationId='+applicationId+'</p>';
		htmlstr+='<p>https://mbdevp1-niimportal.cs58.force.com/NIIMApplication/s/flowapplicationupdate?varApplicationId='+applicationId+'</p>';


		List<Application__c> applications = [SELECT id, name, Medicare_Provider_Number__c, address__c, ABN__c, email__c, Phone_Number__c, Practitioner_s_Name__c, Sites__c, Applied_To_Other_HREC_In_Past_12_Months__c, Commercial_Interest__c, AHPRA_Number__c, Professional_Association_Membership__c, risk_management_strategy__c, status__c, Qualifications_and_Expertise__c,
     (SELECT id, name, App_Good_Indications__c, 
     App_Good_Indications_Description__c, 
     Approved_Good_Alternative__c, Approved_In_Other_Jurisdiction__c, Clinical_Justification__c, Dosage__c, Dosage_Form__c, Dosage_Range__c, Expected_Duration_Of_Treatment__c, Justification_Not_Using_Alternative__c, Product_Trade_Name__c, Product_Company__c, Sponsor__c, Seriousness__c, Tried_Will_Try_Approved_Alternative__c, 
     Active_Ingredients_Concentrations__c FROM App_Goods__r),(select document__c,change_required__c from Concerns__r where status__c='Open')
		 FROM Application__c
		 WHERE id = :applicationId];
		 
		for (Application__c a : applications){
			htmlstr += '<p>============================================</p>';
			htmlstr += '<h2>Changes to your Application Required by NIIM</h2> ';


			if (a.concerns__r.size() > 0) {
				htmlstr+='<p>Please note that to progress your application NIIM requests you make the following changes:</p>';

	for( Changes_Required__c cr: a.concerns__r) {
	
		htmlstr+='<p><b>Document:</b> '+cr.document__c+'</p>';
		htmlstr+='<p><b>Change Required:</b> '+cr.change_required__c+'</p>';
		htmlstr+='<br/>';
	} 
} else {
		htmlstr+='<p><b>There are currently no changes required to your application</p>';


	}
	
			
			
			htmlstr += '<p>============================================</p>';

			htmlstr += '<h2>Practitioner Details</h2>';
			htmlstr += '<p><b>Reference:</b> ' + a.name + '</p>';
			htmlstr += '<p><b>Name:</b> ' + a.Practitioner_s_Name__c + '</p>';
			htmlstr += '<p><b>Address:</b> ' + a.address__c + '</p>';
			htmlstr += '<p><b>Email:</b> ' + a.email__c + '</p>';
			htmlstr += '<p><b>Phone:</b> ' + a.Phone_Number__c + '</p>';
			htmlstr += '<p><b>Medicare Provider No:</b> ' + a.Medicare_Provider_Number__c + '</p>';
			htmlstr += '<p><b>ABN:</b> ' + a.ABN__c + '</p>';
			htmlstr += '<p><b>AHPRA:</b> ' + a.AHPRA_Number__c + '</p>';
			htmlstr += '<p><b>Professional Assoc:</b> ' + a.Professional_Association_Membership__c + '</p>';
			htmlstr += '<p><b>Sites:</b> ' + a.Sites__c + '</p>';
			htmlstr += '<p><b>Has Applied to Other HREC:</b> ' + a.Applied_To_Other_HREC_In_Past_12_Months__c + '</p>';
			htmlstr += '<p><b>Commercial Interests:</b> ' + a.Commercial_Interest__c + '</p>';
			htmlstr += '<p><b>Qualifications and Experience:</b> ' + a.Qualifications_and_Expertise__c + '</p>';

			htmlstr += 
		'<p><b>Risk Management Strategy:</b> ' + a.Risk_Management_Strategy__c + 
		'</p>';
			htmlstr += '<p>============================================</p>';




			htmlstr += '<h2>Unapproved Goods</h2> ';

			for (App_Good__c appgood : a.App_Goods__r){
				htmlstr += '<h3>---- Product Information ------</h3>';

				htmlstr += '<p><b>Good:</b> ' + appgood.name + '</p>';
				htmlstr += '<p><b>Trade Name:</b> ' + appgood.Product_Trade_Name__c + '</p>';
				htmlstr += '<p><b>Company:</b> ' + appgood.Product_Company__c + '</p>';
				htmlstr += '<p><b>Active Ingredients Conc:</b> ' + appgood.Active_Ingredients_Concentrations__c + '</p>';
				htmlstr += '<p><b>Dosage Form:</b> ' + appgood.Dosage_Form__c + '</p>';
				htmlstr += '<p><b>Dosage:</b> ' + appgood.Dosage__c + '</p>';
				htmlstr += '<p><b>Sponsor:</b> ' + appgood.Sponsor__c + '</p>';
				htmlstr += '<p><b>Approved In  Other Jurisdictions:</b> ' + appgood.Approved_In_Other_Jurisdiction__c + '</p>';
				htmlstr += '<h3>---- Indications, Dosage and Justifications ------</h3>';

				htmlstr += '<p><b>Clinical Indications:</b> ' + appgood.App_Good_Indications__c + '</p>';
				htmlstr += '<p><b>Additional Indications Comments:</b> ' + appgood.App_Good_Indications_Description__c + '</p>';
				htmlstr += '<p><b>Seriousness:</b> ' + appgood.Seriousness__c + '</p>';

				htmlstr += '<p><b>Dosage Range:</b> ' + appgood.Dosage_Range__c + '</p>';
				htmlstr += '<p><b>Expected Duration:</b> ' + appgood.Expected_Duration_Of_Treatment__c + '</p>';
				htmlstr += '<p><b>Justification for using unapproved goods:</b> ' + appgood.Clinical_Justification__c + '</p>';
				htmlstr += '<p><b>Is there an approved product:</b> ' + appgood.Approved_Good_Alternative__c + '</p>';
				htmlstr += '<p><b>Have tried/will try the approved :</b> ' + appgood.Tried_Will_Try_Approved_Alternative__c + '</p>';
				htmlstr += '<p><b>Why is the approved good inappropriate :</b> ' + appgood.Justification_Not_Using_Alternative__c + '</p>';


				htmlstr += '<p>-----------------------------------------</p>';
			}
			htmlstr += '<p>============================================</p>';

		}

		List<String> contentids = new List<String>();
		for (ContentDocumentLink cdl : [SELECT ContentDocumentId, LinkedEntityId, LinkedEntity.Name, LinkedEntity.Type, ShareType, Visibility
		                                FROM ContentDocumentLink
		                                WHERE LinkedEntityId IN (SELECT Id
		                                                         FROM Application__C
		                                                         WHERE id = :applicationId) AND LinkedEntity.Type = 'Application__c']){
			Id cvid = [SELECT id, title, versiondata, filetype
			           FROM contentversion
			           WHERE contentdocumentid = :cdl.ContentDocumentId AND IsLatest = TRUE
			           LIMIT 1].Id;
			contentids.add(cvid);
		}
		message.setSubject('Application');
		message.setEntityAttachments(contentids);
		message.setHtmlBody(htmlstr);


		// Send the message
		try{
			Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{message});
		} catch (Exception e){
			throw e;
		}
	}
}