force-app/main/default/objects/App_Good__c/App_Good__c.object-meta.xml
<CustomObject>
    <label>App-Good</label>
    <nameField>
        <displayFormat>AG-{000000}</displayFormat>
        <label>App-Good Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App-Goods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Good__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>App-Goods</relationshipLabel>
    <relationshipName>App_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Product_Trade_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Trade_Name__c</fullName>
    <label>Product Trade Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_Number__c</fullName>
    <label>AHPRA Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Practitioner_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_s_Name__c</fullName>
    <label>Practitioner&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationControllerTest.cls
@isTest
private class ApplicationControllerTest {
  @isTest
  static void myTest() {
    Application__c a = new Application__c(
      email__c = 'burnside.mike@gmail.com',
      Practitioner_s_name__c = 'xx',
      AHPRA_Number__c = 'MED0000000000'
    );
    insert a;
    App_Good__c ag = new App_Good__c(
      Product_Trade_Name__c = 'XXX',
      Application__c = a.Id
    );
    insert ag;
    Test.startTest();
    List<Application__c> listapps = ApplicationController.getApplicationList();
    System.assert(listapps.size() >= 1);

    listapps = ApplicationController.findApplications('Application');
    System.assert(listapps.size() >= 1);

    Application__c app = ApplicationController.getSingleApplication();
    System.assert(app != null);
    Test.stopTest();
  }
}