force-app/main/default/objects/App_Good__c/App_Good__c.object-meta.xml
<CustomObject>
    <label>App-Good</label>
    <nameField>
        <displayFormat>AG-{000000}</displayFormat>
        <label>App-Good Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App-Goods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Good__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>App-Goods</relationshipLabel>
    <relationshipName>App_Goods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/App_Good__c/fields/Product_Trade_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Trade_Name__c</fullName>
    <label>Product Trade Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/AHPRA_Number__c.field-meta.xml
<CustomField>
    <fullName>AHPRA_Number__c</fullName>
    <label>AHPRA Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Practitioner_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Practitioner_s_Name__c</fullName>
    <label>Practitioner&apos;s Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvocableFileListTest.cls
@isTest
private class InvocableFileListTest{
	@isTest
	static void myTest(){
		Application__c a = new Application__c(email__c = 'burnside.mike@gmail.com', Practitioner_s_name__c = 'xx', AHPRA_Number__c = 'MED0000000000');
		insert a;
		App_Good__c ag = new App_Good__c(Product_Trade_Name__c = 'XXX', Application__c = a.Id);
		insert ag;



		String myFileContent = 'Mikes File upload content';

		ContentVersion conVer = new ContentVersion();
		conVer.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
		conVer.PathOnClient = 'test.txt'; // The files name, extension is very important here which will help the file in preview.
		conVer.Title = 'Test File'; // Display name of the files
		conVer.VersionData = EncodingUtil.base64Decode(myFileContent); // converting your binary string to Blog
		insert conVer;    //Insert ContentVersion

		Id conDoc = [SELECT ContentDocumentId
		             FROM ContentVersion
		             WHERE Id = :conVer.Id].ContentDocumentId;
		//create ContentDocumentLink  record
		ContentDocumentLink conDocLink = New ContentDocumentLink();
		conDocLink.LinkedEntityId = a.Id; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
		conDocLink.ContentDocumentId = conDoc;  //ContentDocumentId Id from ContentVersion
		conDocLink.shareType = 'V';
		insert conDocLink;

		Test.startTest();

		InvocableFileList.Request argument;
		argument = new InvocableFileList.Request();
		argument.recordId = a.id;

		List<String> teststr = new List<String>();
		List<List<contentversion>> result = new List<List<contentversion>>();

		result = InvocableFileList.doAction(new List<InvocableFileList.Request>{argument});

		Test.stopTest();
		System.assert(result.size() == 1);


		//System.assert(teststr[0] == 'Completed');
	}
}